version: "3.7"

services:
    home_service:
        image: fhomez/home
        container_name: backend-home-service
        ports:
            - "5001:5001"
        restart: unless-stopped
        # volumes:
        #     - ./app/backend/:/home/fhomez/service
        networks:
            - fhomez-network
    auth_service:
        image: fhomez/auth
        container_name: backend-auth-service
        ports:
            - "8000:8000"
        restart: unless-stopped
        # volumes:
        #     - ./app/backend/:/home/fhomez/service
        networks:
            - fhomez-network
    admin_service:
        image: fhomez/admin
        container_name: backend-admin-service
        ports:
            - "8001:8001"
        restart: unless-stopped
        # volumes:
        #     - ./app/backend/:/home/fhomez/service
        networks:
            - fhomez-network
    chat_service:
        image: fhomez/chat
        container_name: backend-chat-service
        ports:
            - "5000:5000"
        restart: unless-stopped
        # volumes:
        #     - ./app/backend/:/home/fhomez/service
        networks:
            - fhomez-network
    socket_service:
        image: fhomez/socket
        container_name: backend-socket-service
        ports:
            - "8900:8900"
        restart: unless-stopped
        # volumes:
        #     - ./app/backend/:/home/fhomez/service
        networks:
            - fhomez-network
    frontend:
        image: fhomez/frontend
        container_name: frontend
        ports:
            - "3000:3000"
        restart: unless-stopped
        # volumes:
        #     - ./app/backend/:/home/fhomez/service
        networks:
            - fhomez-network
networks:
    fhomez-network:
        driver: bridge
