version: "3.7"

services:
  home_service:
    image: fhomez-home-service/node:v2
    container_name: backend-home-service
    ports:
      - "49160:5001"
    restart: unless-stopped
    volumes:
      - ./app/backend/:/home/fhomez/service
    networks:
      - fhomez-network
  auth_service:
    image: fhomez-home-auth/node:v2
    container_name: backend-auth-service
    ports:
      - "49170:5001"
    restart: unless-stopped
    volumes:
      - ./app/backend/:/home/fhomez/service
    networks:
      - fhomez-network
networks:
  fhomez-network:
    driver: bridge
